### ISSUE TITLE
Tests break across timezones

### ISSUE THREAD

**Issue by AlexChalk** [makersacademy/acebook-remote-april-2017#20]
```ruby
Failures:

  1) Timeline Can submit posts and view them
     Failure/Error: expect(page).to have_content("posted at #{Time.now.strftime('%H:%M')} on #{Time.now.strftime('%d/%m/%Y')}")
       expected to find text "posted at 07:38 on 31/05/2017" in "Home View Posts Post Log In Sign Up Hello, world! posted at 12:38 on 31/05/2017 Comments Add a comment: Commenter Body Acebook All Rights Reserved 2017 ©"
     # ./spec/features/user_can_submit_and_view_posts_spec.rb:10:in `block (2 levels) in <top (required)>'

  2) Post has a time and date
     Failure/Error: expect(new_post.time_stamp).to eq "#{Time.now.strftime('%H:%M')}"

       expected: "07:38"
            got: "12:38"

       (compared using ==)
     # ./spec/models/post_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.6851 seconds (files took 4.48 seconds to load)
26 examples, 2 failures, 8 pending

Failed examples:

rspec ./spec/features/user_can_submit_and_view_posts_spec.rb:4 # Timeline Can submit posts and view them
rspec ./spec/models/post_spec.rb:5 # Post has a time and date
```

**Comment by AlexChalk** [comment]
Fixed.
